services:
  pytube:
    container_name: pytube
    image: pytube:latest
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/pytube
    working_dir: /pytube
    entrypoint: ["/bin/sh","-c"]
    command: 
      - sh -c "pytube https://www.youtube.com/watch?v=zZTQngw8MZE"


## Download video: pytube https://youtube.com/watch?v=2lAe1cqCOXo
## Download playlist: pytube https://www.youtube.com/playlist?list=PLS1QulWo1RIaJECMeUT4LFwJ-ghgoSH6n